// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/functions/v1/functions.proto

package com.google.cloud.functions.v1;

public interface GenerateUploadUrlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.functions.v1.GenerateUploadUrlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The project and location in which the Google Cloud Storage signed URL
   * should be generated, specified in the format `projects/&#42;&#47;locations/&#42;`.
   * </pre>
   *
   * <code>string parent = 1;</code>
   * @return The parent.
   */
  java.lang.String getParent();
  /**
   * <pre>
   * The project and location in which the Google Cloud Storage signed URL
   * should be generated, specified in the format `projects/&#42;&#47;locations/&#42;`.
   * </pre>
   *
   * <code>string parent = 1;</code>
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString
      getParentBytes();
}
